version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: farkor/foodgram_backend:latest
    expose:
      - "8000"
    restart: always
    command: >
      bash -c "python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      python manage.py load_csv_data &&
      gunicorn --bind 0:8000 foodgram.wsgi"
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: farkor/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_value:/var/html/media/
      - static_value:/var/html/static/
    depends_on:
      - backend

volumes:
  static_value:
  media_value:
  postgres: